Add --recursive option to doc sync command
readmeio/rdme pull request #313
Opened 2021-05-25 02:53 UTC by ollyfg

This option causes a simple recursive search of the supplied folder, nothing fancy.

2021-06-21 20:34 UTC, erunion commented
@ollyfg Can you rebase the latest `main` into this branch? We've moved some things around in the process of dropping support for Node 10.

2021-06-23 15:55 UTC, erunion commented
@rahulhegdee This might collide with the work that you're planning on doing, you mind reviewing this? ty

2021-06-28 19:27 UTC, rahulhegdee requested changes
Small fix but otherwise, looks good to me!

2021-07-08 20:38 UTC, ollyfg commented on src/cmds/docs/index.js
>    const { folder, key, version } = opts;
Whoops! Sorry, must have snuck in there while rebasing.

2021-07-08 20:49 UTC, rahulhegdee approved these changes
👍

2021-07-08 22:14 UTC, erunion approved these changes

2021-07-09 17:32 UTC, erunion approved these changes

2021-07-09 17:52 UTC, rahulhegdee approved these changes

2021-07-09 17:54 UTC, merged