feat: add `docs:single`
readmeio/rdme pull request #529
Opened 2022-06-27 19:00 UTC by garrett-wade

| 🚥 Fix RM-XXX |
| :-- |

## 🧰 Changes

- add doc:create command to allow a single markdown file to be synced rather than only supporting an entire directory.
- updated markdown and doc test to reflect changes

## 🧬 QA & Testing

The `doc:create` command can be ran with the `--filepath` attribute being set to a specific markdown file-path and that file will be synced. If the slug already exists then the chance will not be merged.

2022-06-28 00:20 UTC, kanadgupta requested changes
Thanks for the PR @garrett-wade! I still have yet to do a full review but do you mind adding dry run functionality for this command? Ideally we should have feature parity with the main `docs` command.

2022-06-28 11:52 UTC, garrett-wade commented
@kanadgupta added dry run support

2022-06-28 17:34 UTC, garrett-wade commented
@kanadgupta added dry run support

2022-06-30 13:17 UTC, garrett-wade commented
@kanadgupta or @erunion just following up on this PR, in case you have had a change to review further. Thank you.

2022-06-30 17:11 UTC, kanadgupta commented on src/cmds/docs/create.js
> +          debug(`error retrieving data for ${slug}, creating doc`);
We do this in our current `docs` command 😅 my bad lol

https://github.com/readmeio/rdme/blob/e8516b752749f9c3a5ac4af1e1df8ba8a03f3bea/src/cmds/docs/index.js#L172

2022-06-30 17:15 UTC, kanadgupta requested changes
Can you rename this command as described below? And could you merge the `main` branch into this branch? I just merged in #531 which should hopefully get tests running on this PR properly.

2022-06-30 17:15 UTC, kanadgupta commented on src/cmds/docs/create.js
> +    this.command = 'docs:create';
Can you rename this command to `docs:single`? Technically "create" is a bit of a misnomer since this command can create or update a doc.

2022-06-30 17:15 UTC, kanadgupta commented on README.md
> +#### Syncing a single Markdown File to ReadMe
We use [AP-style title casing](https://titlecaseconverter.com/) here:

```suggestion
#### Syncing a Single Markdown File to ReadMe
```

2022-06-30 17:17 UTC, kanadgupta commented on src/cmds/docs/create.js
> +          debug(`error retrieving data for ${slug}, creating doc`);
I think if anything we should be checking for a 404 rather than just any error, but we can consolidate and tweak that logic later.

2022-06-30 17:28 UTC, kanadgupta commented
Ignore [the failing GitHub Action Dry Run workflow](https://github.com/readmeio/rdme/runs/7136562377?check_suite_focus=true), I believe that's because your fork doesn't have the API key secrets configured.

2022-07-01 17:36 UTC, kanadgupta commented on src/cmds/docs/create.js
> +          debug(`error retrieving data for ${slug}, creating doc`);
Dug into this a bit further and we already have a `DOC_NOTFOUND` check so I think we're good on this.

https://github.com/readmeio/rdme/blob/1ba56d1e3c6390cc6af21c1a59fb5ae76ba85077/src/cmds/docs/single.js#L82

2022-07-01 17:40 UTC, merged