test: mock out git
readmeio/rdme pull request #972
Opened 2024-02-07 18:40 UTC by kellyjosephprice

## 🧰 Changes

Speeds up a few tests by mocking out `git` commands.

I was poking around to investigate a bug (https://linear.app/readme-io/issue/RM-8336/childdocs-are-createdsyncd-before-parentdocs-in-rdme-cli) and noticed some test timeouts when running them locally. It looks like for a number of tests, we were making actual requests like `git remote`.

## 🧬 QA & Testing

Tests should pass???

2024-02-07 20:40 UTC, erunion approved these changes
seems ok to me given everything is passing but will let @kanadgupta give the final ✅ before merging

2024-02-12 19:26 UTC, kanadgupta requested changes
oh dang, this is a great catch! i have an idea on how to approach this that _should_ be a one or two line change: what if you grabbed [this logic](https://github.com/readmeio/rdme/blob/58bcc4806197ee176dcf3e232d9ad7a9a31e4d33/src/lib/createGHA/index.ts#L181) and moved it up to [this if-statement](https://github.com/readmeio/rdme/blob/58bcc4806197ee176dcf3e232d9ad7a9a31e4d33/src/lib/createGHA/index.ts#L159-L162)? i think you should be able to revert most of the logic you wrote here!

2024-02-14 23:44 UTC, kanadgupta approved these changes
amazing, LGTM! are you still seeing the perf benefits?

2024-02-14 23:44 UTC, kanadgupta commented on src/lib/createGHA/index.ts
> +    debug('not running GHA onboarding workflow in CI, npm script, or default test env, exiting 👋');
👋🏽

2024-02-15 00:38 UTC, kellyjosephprice commented
> amazing, LGTM! are you still seeing the perf benefits?

Yea, it looked like the exact same time for test runs.

2024-02-15 00:38 UTC, merged

2024-12-06 15:55 UTC, kanadgupta commented
:tada: This PR is included in version 9.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/rdme/v/9.0.0)
- `v9.0.0`
- [GitHub release](https://github.com/readmeio/rdme/releases/tag/v9.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: